[package]
name = "render-magic"
version = "0.1.0"
authors = ["jaime"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
